spring.application.name=Homebank
spring.profiles.active=@spring.profiles.active@

jwt.access.duration=10
jwt.recovery.duration=10

auth.activation-token.duration-hours=24
auth.refresh-token.duration-days=7
